Vagrant.configure("2") do |config|
  # For a complete reference, follow this link https://docs.vagrantup.com.
  # About boxes, look at https://vagrantcloud.com/search.

  # Environment
  config.vm.box = "ubuntu/focal64"

  # Network
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.1.130"
  # config.vm.network "private_network", type: "dhcp"
  config.vm.network "public_network", ip: "192.168.0.241"

  # Desabling default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Enabling custom synced folder
  config.vm.synced_folder "./ssh_keys", "/ssh_keys"

  # Shell scripts
  config.vm.provision "shell", path: "./shellscripts/install_apps_post_config.sh"
  config.vm.provision "shell", path: "./shellscripts/ssh_config.sh"
  #
end
