Vagrant.configure("2") do |config|
  # For a complete reference, follow this link https://docs.vagrantup.com.
  # About boxes, look at https://vagrantcloud.com/search.

  # Environment
  config.vm.box = "ubuntu/focal64"

  config.vm.define "mysqldb" do |mysql|
    # Network
    # mysql.vm.network "forwarded_port", guest: 80, host: 8080
    mysql.vm.network "public_network",
      bridge: "wlp2s0",
      ip: "192.168.0.241"

    # Desabling default synced folder
    mysql.vm.synced_folder ".", "/vagrant", disabled: true

    # Enabling custom synced folder
    mysql.vm.synced_folder "./ssh_keys", "/ssh_keys"
    mysql.vm.synced_folder "./mysql_config", "/mysql_config"

    # Shell scripts
    mysql.vm.provision "shell", path: "./shellscripts/ssh_config.sh"
    mysql.vm.provision "shell", path: "./shellscripts/install_apps_post_config.sh"
    mysql.vm.provision "shell", path: "./shellscripts/mysql-server-8.0_configuration.sh"
  end

  config.vm.define "phpweb" do |phpweb|
    # Network
    phpweb.vm.network "forwarded_port",
      guest: 80,
      host: 8080
    phpweb.vm.network "public_network",
      bridge: "wlp2s0",
      ip: "192.168.0.242"

    # Desabling default synced folder
    phpweb.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
